name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 创建版本号
  increment-version:
    name: Increment Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.NEW_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Increment version
        id: set-version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.3.7")
          MAJOR=$(echo $VERSION | awk -F. '{print $1}' | sed 's/v//')
          MINOR=$(echo $VERSION | awk -F. '{print $2}')
          PATCH=$(echo $VERSION | awk -F. '{print $3}')
          PATCH=$((PATCH + 1))
          if [ "$PATCH" -gt 9 ]; then
            PATCH=0
            MINOR=$((MINOR + 1))
          fi
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"
  # macOS 端打包并上传到 GitHub Release
  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    needs: increment-version
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm run install-all

      - name: Run common build
        run: npm run build

      - name: Run macOS API build
        run: npm run build:api:macos

      - name: Run macOS build
        run: npm run electron:build -- --mac --x64

      - name: Rename macOS artifacts
        run: |
          mv "./dist_electron/MoeKoe Music.dmg" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-x64.dmg"
          mv "./dist_electron/MoeKoe Music.zip" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-x64.zip"
      
      - name: List files after renaming
        run: ls -al ./dist_electron

      - name: Upload macOS artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.increment-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ needs.increment-version.outputs.version }}"
          body: ${{ env.COMMIT_MESSAGE }}
          prerelease: false
          files: |
            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-x64.dmg
            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-x64-mac.zip
